
### Script to process .idat files to make expression matrix -------------------------------------------------

# IDAT files are a proprietary format used to store data from Illumina's BeadArray technology. 
# The files are generated by Illumina scanners and contain summary intensities for each probe on an array. 

# Dataset link -
# https://www.ebi.ac.uk/biostudies/arrayexpress/studies/E-MTAB-11975


# BiocManager::install(c("minfi", "limma", "illuminaio", "IlluminaHumanMethylationEPICmanifest", "IlluminaHumanMethylationEPICanno.ilm10b4.hg19"))
library(minfi)
library(illuminaio)
library(IlluminaHumanMethylationEPICmanifest)
library(IlluminaHumanMethylationEPICanno.ilm10b4.hg19)

idat.dir <- "C:/Ankur_IIITD/Bioinfo_Basics/microarray_raw_data_processing/E_MTAB_11975_Alzheimers"

# List all IDAT files
idat.files <- list.files(path = idat.dir, pattern = "*.idat$", full.names = TRUE)

# Extract unique base names
samples <- unique(sub("_(Grn|Red)\\.idat$", "", basename(idat.files)))

# Read all IDAT files
RGset <- read.metharray.exp(base = idat.dir)

# Preprocessing of raw data
MSet <- preprocessIllumina(RGset)

# getBeta: used to calculate the methylation beta values from a MethylSet object, which represents Illumina Infinium DNA methylation array data.
# It returns a matrix where each row corresponds to a probe and each column represents a sample, containing the calculated beta values for each probe-sample combination.
# Beta value = Methylated signal / (Methylated signal + Unmethylated signal)
expr.mat <- getBeta(MSet)

# getM: used to calculate the M-value for each probe on an Illumina methylation array, which represents the log ratio of the methylated signal intensity to the unmethylated signal intensity.
# essentially providing a measure of the methylation level at each locus.
# M = log2(Methylated Signal / Unmethylated Signal) 
Mvals <- getM(MSet)

# Load annotation data for probe-to-gene mapping
annotation <- getAnnotation(IlluminaHumanMethylationEPICanno.ilm10b4.hg19)

# Extract probe ID to gene mapping
probe_to_gene <- annotation[, c("Name", "UCSC_RefGene_Name")]

# Convert probe-to-gene mapping into a named vector
probe_to_gene_map <- setNames(probe_to_gene$UCSC_RefGene_Name, probe_to_gene$Name)

# Convert probe IDs to gene names in the expression matrix
rownames(expr.mat) <- probe_to_gene_map[rownames(expr.mat)]

# Remove NA (probes that don't map to genes)
expr.mat <- expr.mat[!is.na(rownames(expr.mat)), ]

# Save final expression matrix to a CSV file
write.csv(expr.mat, "Expression_Matrix.csv", row.names = TRUE)
